### ISSUE TITLE
Missing "Pro" dataset csv

### ISSUE THREAD

**Issue by gizmochief7** [myrthings/catscatter#1]
I want to duplicate your "Pro" example as demonstrated in the blog using your top-european-investors-seed-rounds-15–19.csv file but I could not find it in the repo. Can you provide it in this repo?

**Comment by myrthings** [comment]
I cannot upload the dataset for that example because we paid for the source data. I can only give you how it looks like so you can try it with your own datasets.

![image](https://user-images.githubusercontent.com/42479943/78873422-262f6e80-7a4b-11ea-9098-fd0b584ea3eb.png)
